### ISSUE TITLE
@Driesboy

### ISSUE THREAD

**Issue by remotevase** [GameCraftPE/Spleef#2]
Bonjour!
1. Pre-aujourd hui, je n'sais pas que tu es la similare age comments moi, et que tu es d'Belgium!
2. Es de que tu parle en française?

**Comment by Driesboy** [comment]
i am 13 years old and speak dutch not française

**Comment by remotevase** [comment]
WAAAH!

**Comment by remotevase** [comment]
lol

**Comment by Driesboy** [comment]
?
